package dev.whyoleg.ktd.api

import kotlinx.serialization.*

/**
 * Points to a file
 */
@Serializable
sealed class TdInputFile : TdObject {
    /**
     * A file defined by its unique ID
     *
     * @property id Unique file identifier
     */
    @Serializable
    @SerialName("inputFileId")
    data class Id(
        @SerialName("id")
        val id: Int
    ) : TdInputFile()

    /**
     * A file defined by its remote ID
     * The remote ID is guaranteed to be usable only if the corresponding file is still accessible to the user and known to TDLib
     * For example, if the file is from a message, then the message must be not deleted and accessible to the user
     * If the file database is disabled, then the corresponding object with the file must be preloaded by the client
     *
     * @property id Remote file identifier
     */
    @Serializable
    @SerialName("inputFileRemote")
    data class Remote(
        @SerialName("id")
        val id: String
    ) : TdInputFile()

    /**
     * A file defined by a local path
     *
     * @property path Local path to the file
     */
    @Serializable
    @SerialName("inputFileLocal")
    data class Local(
        @SerialName("path")
        val path: String
    ) : TdInputFile()

    /**
     * A file generated by the client
     *
     * @property originalPath Local path to a file from which the file is generated
     *                        May be empty if there is no such file
     * @property conversion String specifying the conversion applied to the original file
     *                      Should be persistent across application restarts
     *                      Conversions beginning with '#' are reserved for internal TDLib usage
     * @property expectedSize Expected size of the generated file
     *                        0 if unknown
     */
    @Serializable
    @SerialName("inputFileGenerated")
    data class Generated(
        @SerialName("original_path")
        val originalPath: String,
        @SerialName("conversion")
        val conversion: String,
        @SerialName("expected_size")
        val expectedSize: Int
    ) : TdInputFile()
}
