package dev.whyoleg.ktd.cli.api.tl

const val doubleSlashToken = "//"
const val functionsToken = "---functions---"
const val descriptionAddressToken = "@description"
const val classAddressToken = "@class"
const val dashToken = "-"
const val addressToken = "@"
const val spaceToken = " "
const val emptyToken = ""
const val equalToken = "="
const val descriptionToken = "description"
const val descriptionParamToken = "param_description"
const val slashDashToken = "//-"
const val questionToken = "?"
