name: Check build
on:
  release:
    types: [published]

env:
  GRADLE_VERSION: 5.6.4
  bintray_user: ${{secrets.bintray_user}}
  bintray_key: ${{secrets.bintray_key}}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and upload to bintray
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: publishBintrayRelease --info