name: Upload artifacts to bintray
on:
  pull_request:
    types: [opened]
    branches:
      - master

env:
  GRADLE_VERSION: 5.6.4
  BUCKET: ${{ secrets.scaleway_bucket }}
  ENDPOINT: ${{ secrets.scaleway_endpoint }}
  AWS_ACCESS_KEY_ID: ${{ secrets.scaleway_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.scaleway_secret_key }}
  AWS_DEFAULT_REGION: ${{ secrets.scaleway_region }}
  bintray_user: ${{secrets.bintray_user}}
  bintray_key: ${{secrets.bintray_key}}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download libs
        uses: actions/aws/cli@master
        with:
          args: s3 cp s3://${{ env.BUCKET }}/libs/${{ env.TD_API_VERSION }} libs --recursive --endpoint-url ${{ env.ENDPOINT }}

      # TODO hack for tests
      - run: cp libs client/raw/libs

      - name: Build and upload to bintray
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: bintrayUpload --info
