name: Build JNI
on:
  push:
    branches:
      - github-fetching
jobs:
  download-gperf:
    env:
      BUCKET: ${{ secrets.scaleway_bucket }}
      ENDPOINT: ${{ secrets.scaleway_endpoint }}
      AWS_ACCESS_KEY_ID: ${{ secrets.scaleway_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.scaleway_secret_key }}
      AWS_DEFAULT_REGION: ${{ secrets.scaleway_region }}

    runs-on: ubuntu-latest
    steps:
      - name: Download gperf
        uses: actions/aws/cli@master
        with:
          args: s3api get-object --bucket ${{ env.BUCKET }} --endpoint-url ${{ env.ENDPOINT }} --key build/gperf-win/gperf.exe gperf.exe
      - name: Save gperf
        uses: actions/upload-artifact@v1
        with:
          name: gperf
          path: gperf.exe

  generate-api:
    env:
      TD_API_VERSION: 1.5.0
      GRADLE_VERSION: 5.6.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build generator
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: :api:generator:build
      - name: Generate api ${{ env.TD_API_VERSION }}
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: :api:generator:generateApi -PTD_API_VERSION=${{ env.TD_API_VERSION }}
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: build

  generate-jni:
    env:
      TD_API_VERSION: 1.5.0
      GRADLE_VERSION: 5.6.4

    runs-on: ${{ matrix.os }}
    needs: download-gperf
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86, x64]
        exclude:
          - os: macos-latest
            arch: x86
          - os: ubuntu-latest
            arch: x86

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build generator
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: :api:generator:build

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install make zlib1g-dev libssl-dev gperf libc++abi-dev ccache -y

      - name: Install MacOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew install gperf coreutils

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg.exe install openssl:${{ matrix.arch }}-windows zlib:${{ matrix.arch }}-windows

      - name: Download gperf
        if: matrix.os == 'windows-latest'
        uses: actions/download-artifact@v1
        with:
          name: gperf

      - name: Generate jni ${{ env.TD_API_VERSION }}
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: :api:generator:generateJni -PTD_API_VERSION=${{ env.TD_API_VERSION }} -PARCH=${{ matrix.arch }}

      - name: Show files
        if: matrix.os == 'windows-latest'
        run: |
          dir
          cd api/generator/jni/bin
          dir

      - name: Show files
        if: matrix.os != 'windows-latest'
        run: |
          ls
          cd api/generator/jni/bin
          ls

      - name: Save tdlib
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: api/generator/jni/libs

  upload-tdlib:
    env:
      BUCKET: ${{ secrets.scaleway_bucket }}
      ENDPOINT: ${{ secrets.scaleway_endpoint }}
      AWS_ACCESS_KEY_ID: ${{ secrets.scaleway_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.scaleway_secret_key }}
      AWS_DEFAULT_REGION: ${{ secrets.scaleway_region }}

    runs-on: ubuntu-latest
    needs: generate-jni
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: ubuntu-latest-x64

      - uses: actions/download-artifact@v1
        with:
          name: macos-latest-x64

      - uses: actions/download-artifact@v1
        with:
          name: windows-latest-x64

      - uses: actions/download-artifact@v1
        with:
          name: windows-latest-x86


