name: Check AWS
on:
  push:
    branches:
      - github-fetching
jobs:
  build:
    env:
      BUCKET: ${{ secrets.scaleway_bucket }}
      ENDPOINT: ${{ secrets.scaleway_endpoint }}
      AWS_ACCESS_KEY_ID: ${{ secrets.scaleway_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.scaleway_secret_key }}
      AWS_DEFAULT_REGION: ${{ secrets.scaleway_region }}

    runs-on: ubuntu-latest
    steps:
      - name: Download file
        uses: actions/aws/cli@master
        with:
          args: s3api get-object --bucket ${{ env.BUCKET }} --endpoint-url ${{ env.ENDPOINT }} --key build/gperf-win/gperf.exe gperf.exe

      - name: Copy file
        run: |
          mkdir folder
          cp gperf.exe folder/gperf.exe
          cp gperf.exe gperf1.exe

      - name: Copy files
        uses: actions/aws/cli@master
        with:
          args: s3 cp . s3://${{ env.BUCKET }}/build/test --recursive --endpoint-url ${{ env.ENDPOINT }}

      - name: Show AWS files
        uses: actions/aws/cli@master
        with:
          args: s3 ls s3://${{ env.BUCKET }}/build/test/ --endpoint-url ${{ env.ENDPOINT }}

      - name: Show AWS files
        uses: actions/aws/cli@master
        with:
          args: s3 ls s3://${{ env.BUCKET }}/build/test/folder/ --endpoint-url ${{ env.ENDPOINT }}
