name: Check build
on: push

env:
  GRADLE_VERSION: 5.6.4
  TD_API_VERSION: 1.5.1
  BUCKET: ${{ secrets.scaleway_bucket }}
  ENDPOINT: ${{ secrets.scaleway_endpoint }}
  AWS_ACCESS_KEY_ID: ${{ secrets.scaleway_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.scaleway_secret_key }}
  AWS_DEFAULT_REGION: ${{ secrets.scaleway_region }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download libs
        uses: actions/aws/cli@master
        with:
          args: s3 cp s3://${{ env.BUCKET }}/libs/${{ env.TD_API_VERSION }} client/raw/libs --recursive --endpoint-url ${{ env.ENDPOINT }}
      - run: |
          ls
          cd client/raw
          ls
          cd libs/linux
          ls

      - name: Build and run tests
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: check --info
