name: Build JNI
on:
  push:
    branches:
      - github-fetching
jobs:
  build:
    env:
      TD_API_VERSION: 1.5.0
      GRADLE_VERSION: 5.6.4
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: build
      - name: Generate api 1.5.0
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: :api:generator:generateApi -PTD_API_VERSION=1.5.0
      - name: Generate jni 1.5.0
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: :api:generator:generateJni -PTD_API_VERSION=1.5.0