name: Build tdlib
on:
  push:
    branches:
#      - tdlib/[0-9]+.[0-9]+.[0-9]+
      - tdlib-build

env:
  BUCKET: ${{ secrets.scaleway_bucket }}
  ENDPOINT: ${{ secrets.scaleway_endpoint }}
  AWS_ACCESS_KEY_ID: ${{ secrets.scaleway_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.scaleway_secret_key }}
  AWS_DEFAULT_REGION: ${{ secrets.scaleway_region }}
  TD_API_VERSION: 1.5.0
  JAVA_VERSION: 11.0.5

jobs:

  extract-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(process.env);
            const fs = require('fs');
            const versions = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
            const versions2 = JSON.parse(fs.readFileSync('tdVersions.json', 'utf8'));
            console.log(versions);
            console.log(versions2);

  download-android-openssl:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: aws s3 cp s3://${{ env.BUCKET }}/build/android/openssl.7z . --endpoint-url ${{ env.ENDPOINT }}
      - uses: actions/upload-artifact@v1
        with:
          name: android-openssl
          path: openssl.7z

  download-windows-dependencies:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: aws s3 cp s3://${{ env.BUCKET }}/build/windows/dependencies.7z . --endpoint-url ${{ env.ENDPOINT }}
      - uses: actions/upload-artifact@v1
        with:
          name: windows-dependencies
          path: dependencies.7z

  download-cli:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: aws s3 cp s3://${{ env.BUCKET }}/cli/cli.jar . --endpoint-url ${{ env.ENDPOINT }}
      - uses: actions/upload-artifact@v1
        with:
          name: cli
          path: cli.jar

  generate-mac:
    needs: [download-cli]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: tdlib/td
          path: td
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - run: brew install gperf coreutils ninja
      - uses: actions/download-artifact@v1
        with:
          name: cli

      - name: Generate tdlib
        run: java -jar cli/cli.jar tdlib -v ${{ env.TD_API_VERSION }} -p jvm -t mac -c cli/config/tdlib.default.conf

      - uses: actions/upload-artifact@v1
        with:
          name: mac
          path: tdlib/jni/bin

  generate-win:
    needs: [download-cli, download-windows-dependencies]
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: tdlib/td
          path: td
      - uses: actions/checkout@v2
        with:
          repository: Microsoft/vcpkg
          path: vcpkg
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/download-artifact@v1
        with:
          name: cli
      - uses: actions/download-artifact@v1
        with:
          name: windows-dependencies
      - run: |
          cd windows-dependencies
          7z x dependencies.7z -y
          xcopy /S dependencies ..\

      - name: Generate tdlib
        run: java -jar cli/cli.jar tdlib -v ${{ env.TD_API_VERSION }} -p jvm -t win-${{ matrix.arch }} -c cli/config/tdlib.default.conf

      - name: Save tdlib
        uses: actions/upload-artifact@v1
        with:
          name: win-${{ matrix.arch }}
          path: tdlib/jni/bin

  generate-linux:
    needs: [download-cli]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: tdlib/td
          path: td
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - run: sudo apt install make zlib1g-dev libssl-dev gperf libc++abi-dev ccache ninja-build -y
      - uses: actions/download-artifact@v1
        with:
          name: cli

      - name: Generate tdlib
        run: java -jar cli/cli.jar tdlib -v ${{ env.TD_API_VERSION }} -p jvm -t linux -c cli/config/tdlib.default.conf

      - name: Save tdlib
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: tdlib/jni/bin

  generate-android:
    needs: [download-cli, download-android-openssl]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [armv7, armv8, x86, x64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: tdlib/td
          path: td
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: jre

      - run: sudo apt install make zlib1g-dev libssl-dev gperf libc++abi-dev ccache ninja-build -y
      - uses: actions/download-artifact@v1
        with:
          name: android-openssl
      - uses: actions/download-artifact@v1
        with:
          name: cli
      - run: |
          cd android-openssl
          7z x openssl.7z -y
          cp -r openssl ..

      - name: Generate tdlib
        run: java -jar cli/cli.jar tdlib  -v ${{ env.TD_API_VERSION }} -p jvm -t android-${{ matrix.arch }} -c cli/config/tdlib.default.conf

      - name: Save tdlib
        uses: actions/upload-artifact@v1
        with:
          name: android-${{ matrix.arch }}
          path: tdlib/jni/bin

  #TODO create action to iterate over platforms/targets
  upload-tdlib:
    runs-on: ubuntu-latest
    needs: [generate-linux, generate-win, generate-mac, generate-android]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: linux
          path: tdlib/linux

      - uses: actions/download-artifact@v1
        with:
          name: mac
          path: tdlib/mac

      - uses: actions/download-artifact@v1
        with:
          name: win-x64
          path: tdlib/win-x64

      - uses: actions/download-artifact@v1
        with:
          name: win-x86
          path: tdlib/win-x86

      - uses: actions/download-artifact@v1
        with:
          name: android-armv7
          path: tdlib/android-armv7

      - uses: actions/download-artifact@v1
        with:
          name: android-armv8
          path: tdlib/android-armv8

      - uses: actions/download-artifact@v1
        with:
          name: android-x86
          path: tdlib/android-x86

      - uses: actions/download-artifact@v1
        with:
          name: android-x64
          path: tdlib/android-x64

      - run: ls -lahR
      - run: ls tdlib -lahR
#      - name: Upload libs
#        run: aws s3 cp libs s3://${{ env.BUCKET }}/tdlib/${{ env.TD_API_VERSION }} --recursive --endpoint-url ${{ env.ENDPOINT }}
